version: 3

# silent: true

dotenv: [".env"]

tasks:
  docker-mongo-run:
    cmds:
      - docker run --name mongo   -p 27017:27017  -d mongodb/mongodb-community-server:latest

  seed: go run ./scripts
  build:
    cmds:
      - go build -o ./bin/api ./api 
  run:
    deps: [build]
    cmds:
      - ./bin/api {{.CLI_ARGS}}

  test:
    cmds:
      - go test ./...  -v -count=1
